-- conversion: SCM_FABIN_CONV_FAM6_MST_M
-- UNION ALL로 DRAM/FLASH 분리, unit(UOM)으로 구분
-- K4=DRAM, PD=DRAM(MCP), K9=FLASH, 그외=OTHER
-- 복합칩(예: KM8L9001JA-HJABST)은 DRAM행+FLASH행 2행 생성
-- QTY/BOX 중복 없음: conversion은 환산계수만 제공, 입고 행은 별도

SELECT ITEM, SUM(EQQTY) AS EQQTY, 'PC-DRAM' AS UNIT, 'Y' AS USE_FLAG
FROM SCM_INFO.SCM_FABIN_CONV_FAM6_MST_M
WHERE USE_FLAG='Y' AND EQQTY > 0
  AND (CONV_CODE LIKE 'K4%' OR CONV_CODE LIKE 'PD%')
  AND EXISTS (SELECT 1 FROM MST_PAX_ITEM p WHERE p.ITEM = SCM_INFO.SCM_FABIN_CONV_FAM6_MST_M.ITEM)
GROUP BY ITEM

UNION ALL

SELECT ITEM, SUM(EQQTY) AS EQQTY, 'PC-FLASH' AS UNIT, 'Y' AS USE_FLAG
FROM SCM_INFO.SCM_FABIN_CONV_FAM6_MST_M
WHERE USE_FLAG='Y' AND EQQTY > 0
  AND CONV_CODE LIKE 'K9%'
  AND EXISTS (SELECT 1 FROM MST_PAX_ITEM p WHERE p.ITEM = SCM_INFO.SCM_FABIN_CONV_FAM6_MST_M.ITEM)
GROUP BY ITEM

UNION ALL

SELECT ITEM, SUM(EQQTY) AS EQQTY, 'PC-OTHER' AS UNIT, 'Y' AS USE_FLAG
FROM SCM_INFO.SCM_FABIN_CONV_FAM6_MST_M
WHERE USE_FLAG='Y' AND EQQTY > 0
  AND CONV_CODE NOT LIKE 'K4%' AND CONV_CODE NOT LIKE 'PD%' AND CONV_CODE NOT LIKE 'K9%'
  AND EXISTS (SELECT 1 FROM MST_PAX_ITEM p WHERE p.ITEM = SCM_INFO.SCM_FABIN_CONV_FAM6_MST_M.ITEM)
GROUP BY ITEM
