-- inbound_plan: GUI_F_FORECAST_WEEK (F=실시간, 주별 생산계획)
-- PLANID = TO_CHAR(SYSDATE-3, 'IYYYIW') (3일전 주차 = 목요일 버전)
-- MEASURE = 'PRODUCTION' (생산계획)
-- FMONTH = TO_CHAR(SYSDATE, 'YYYYMM') (당월)
-- FWEEK별 생산계획을 ITEM/SITEID/PRODUCTGROUP 단위로 집계
SELECT PLANID,
       FMONTH,
       FWEEK,
       ITEM,
       SITEID,
       PRODUCTGROUP,
       PRODUCT,
       SUM(FCST_QTY) AS FCST_QTY
FROM GUI_F_FORECAST_WEEK
WHERE PLANID = TO_CHAR(SYSDATE - 3, 'IYYYIW')
  AND MEASURE = 'PRODUCTION'
  AND FMONTH = TO_CHAR(SYSDATE, 'YYYYMM')
GROUP BY PLANID, FMONTH, FWEEK, ITEM, SITEID, PRODUCTGROUP, PRODUCT
