-- pslink: TAR_BSCMPSLINK
-- FROM_PROD_CODE(TO_PROD_CODE) 품목코드 매핑 (PP_TYPE: EFU=출하/실제, TFN=plan/W0000, ABD=상세, FM1/FM2=조립)
-- actual(EFU) → plan(TFN/W0000) 변환용

SELECT FROM_PROD_CODE, FROM_PP_TYPE, TO_PROD_CODE, TO_PP_TYPE
FROM MEMSCM.TAR_BSCMPSLINK
WHERE DEL_FLAG = 'N'
