-- shipment_plan: TAR_D_PLAN_SELL_ESCM
-- CONV_FLAG='C' AND COMPANY_TYPE='S'
-- SPMON=최신 (수집월) AND PLAN_YYYYMM=당월 (계획대상월)
-- 집계: SPMON/PLAN_YYYYMM/PLAN_NAME/DATA_FLAG/ITEM_CODE/GC_CODE/CONS_ITEM_CODE 기준 SUM
-- (SOLD_TO 등 하위 차원 중복 제거)
SELECT SPMON, PLAN_YYYYMM, PLAN_NAME, DATA_FLAG,
       ITEM_CODE, GC_CODE, GC_DESC,
       CONS_ITEM_CODE,
       FAMILY1, FAMILY4, FAMILY5,
       GFAMILY1,
       SUM(PLAN_QTY) AS PLAN_QTY,
       SUM(CONS_QTY) AS CONS_QTY,
       SUM(MEMORY_EQ_QTY) AS MEMORY_EQ_QTY,
       SUM(GFAM1_EQ_QTY) AS GFAM1_EQ_QTY,
       SUM(USD_AMT) AS USD_AMT,
       SUM(LOCAL_AMT) AS LOCAL_AMT,
       SUM(KRW_AMT) AS KRW_AMT,
       MAX(UNIT_PRICE) AS UNIT_PRICE,
       MAX(CONS_PRICE) AS CONS_PRICE,
       MAX(MCP_FLAG) AS MCP_FLAG,
       MAX(BRAND_FLAG) AS BRAND_FLAG,
       MAX(CURRENCY) AS CURRENCY,
       MAX(USD_EX_RATE) AS USD_EX_RATE,
       MAX(GFAMILY2) AS GFAMILY2,
       MAX(GFAMILY3) AS GFAMILY3,
       MAX(GFAMILY4) AS GFAMILY4,
       MAX(GFAMILY5) AS GFAMILY5,
       MAX(CATG) AS CATG,
       MAX(COMPANY_CODE) AS COMPANY_CODE,
       MAX(CORP_NAME) AS CORP_NAME,
       MAX(MOD) AS MOD,
       MAX(CONS_SEQ) AS CONS_SEQ,
       MAX(DESIGN_RULE) AS DESIGN_RULE,
       MAX(MOD_TYPE) AS MOD_TYPE,
       MAX(MOD_DENSITY) AS MOD_DENSITY,
       MAX(MADE_DTTM) AS MADE_DTTM,
       MAX(MADE_TYPE) AS MADE_TYPE,
       MAX(MADE_KIND) AS MADE_KIND,
       MAX(BRAND_ITEM) AS BRAND_ITEM,
       MAX(BRAND_CUST) AS BRAND_CUST,
       MAX(SOLD_TO) AS SOLD_TO,
       MAX(SOLD_TO_DESC) AS SOLD_TO_DESC,
       MAX(CONV_FLAG) AS CONV_FLAG,
       MAX(COMPANY_TYPE) AS COMPANY_TYPE,
       MAX(LOCAL_EX_RATE) AS LOCAL_EX_RATE,
       MAX(CONS_RATE) AS CONS_RATE
FROM TAR_D_PLAN_SELL_ESCM
WHERE CONV_FLAG = 'N'
  AND COMPANY_TYPE = 'S'
  AND SPMON = (SELECT MAX(SPMON) FROM TAR_D_PLAN_SELL_ESCM WHERE CONV_FLAG = 'C' AND COMPANY_TYPE = 'S')
  AND PLAN_YYYYMM = TO_CHAR(SYSDATE, 'YYYYMM')
GROUP BY SPMON, PLAN_YYYYMM, PLAN_NAME, DATA_FLAG,
         ITEM_CODE, GC_CODE, GC_DESC, CONS_ITEM_CODE,
         FAMILY1, FAMILY4, FAMILY5, GFAMILY1
